### ISSUE TITLE
Matrix Gateway : Rejected list : null to empty array

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/common-proxies#13]
The specification https://matrix.org/docs/spec/push_gateway/r0.1.1 requires "A list of all pushkeys given in the notification request that are not valid. [...] May be empty."
So, if no pushkey is invalid it should return `{"rejected":[]}`.
Currently it returns `{"rejected":null}` (and gives an error on element-android when it sends itself the notif to troubleshoot).

**Comment by karmanyaahm** [comment]
Fixed by b57164be0704df7bf025f3d8f95696cfecf55fd7..32e978ac73f4a8951621326d93e31ebf1ddc8a7f
