### ISSUE TITLE
Support new FCM API

### ISSUE THREAD

**Issue by provokateurin** [UnifiedPush/common-proxies#47]

**Comment by p1gp1g** [comment]
What do you mean by new api/legacy api ?

If it is about the "/v2" rewrite proxy for FCM and the previous rewrite proxy, they are both working at this moment :)

**Comment by jld3103** [comment]
No I mean this:
![Screenshot_20220718_125951](https://user-images.githubusercontent.com/26026535/179497923-0e7f4648-cd40-4919-9e4f-69bd01c04505.png)
I had to enable the legacy API to get the proxy to work.  
The new API should be supported and how to use the legacy API should be documented, because it took me a while to figure it out.

**Comment by moffatman** [comment]
Can we re-open this, I got a warning email from google, they are not going to support either the legacy HTTP protocol or server keys after June 20, 2024

**Comment by karmanyaahm** [comment]
Yikes

**Comment by karmanyaahm** [comment]
Did it contain any links with more details?

**Comment by moffatman** [comment]
https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by moffatman** [comment]
Anyone planning to fix this... approx 3 months until taken down

**Comment by karmanyaahm** [comment]
I'll put a call out in the UP chat, or I'll try to do it soon if not

**Comment by moffatman** [comment]
@karmanyaahm I opened a PR, it seems to work for me. But I appreciate some review as this is my first ever Go code

**Comment by karmanyaahm** [comment]
Thank you so much! I will take a look this week

**Comment by karmanyaahm** [comment]
reopening to track fixing the things @p1gp1g suggested https://github.com/UnifiedPush/common-proxies/pull/66#issuecomment-2095305345

**Comment by p1gp1g** [comment]
This is good as it is, the users will notice they need to migrate :+1: 

We should release a new version soon cf #67
