### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by p1gp1g** [UnifiedPush/common-proxies#67]
The FCM rewrite proxy has a non-backward compatible change: it will be a major release then. We should link https://firebase.google.com/docs/cloud-messaging/migrate-v1 to the release.

BTW, I suggest we remove the gotify rewrite proxy at the same time, what do you think @karmanyaahm ?

**Comment by karmanyaahm** [comment]
I can make a release and a post on mastodon

**Comment by karmanyaahm** [comment]
Release is building now!
