### ISSUE TITLE
Internal DNS server

### ISSUE THREAD

**Issue by Schnilz** [UnifiedPush/common-proxies#8]
I run an internal DNS for services (e.g. gotify) which are also externally available.
I think Paranoidhttp prevents the proxy to connect to my gotify instance, as the internal DNS resolves the domain to my internal ip address.
The logs show following error:
```
panic:
Post "https://push.example.com/UP?token=asdbc1234": bad ip is detected: 192.168.0.10
```

**Comment by karmanyaahm** [comment]
That is for security reasons because the gateway can connect to arbritary internal URLs. I'll see if I can add an allowed IPs or domains list.
